---
branches:
- development
plugins:
- - "@semantic-release/exec"
  - prepareCmd: |-
      ./bin/container_build.sh
- - "@semantic-release/commit-analyzer"
  - preset: angular
- - "@semantic-release/release-notes-generator"
  - preset: angular
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
    message: |-
      chore(release): ${nextRelease.version} [skip ci]

      ${nextRelease.notes}
- - "@semantic-release/exec"
  - verifyConditionsCmd: |-
      echo 'Publishing site'
    publishCmd: |-
       ./bin/container_publish.sh "Publish version ${nextRelease.version} at ${Date.now()}"
